name: EasyJetpack
main: com.github.jselby.EasyJetpack.EasyJetpack
version: 0.5
permissions:
   easyjetpack.*:
      description: All permissions in EasyJetpack
      children:
        easyjetpack.softlanding: true
        easyjetpack.fly: true
        easyjetpack.fuelless: true
   easyjetpack.softlanding:
      description: Enables the use of anti-fall damage boots
      default: op
   easyjetpack.fly:
      description: Enables the use of the jetpack
      default: op
   easyjetpack.fuelless:
      description: Fly without fuel
      default: op
commands:
   easyjetpack:
      description: EasyJetpack commands
      usage: /easyjetpack reload
      permission: easyjetpack.reload