name: EasyJetpack
main: com.github.jselby.EasyJetpack.EasyJetpack
version: 0.2
permissions:
   easyjetpack.*:
      description: All permissions in EasyJetpack
      children:
        easyjetpack.softlanding: true
        easyjetpack.fly: true
   easyjetpack.softlanding:
      description: Enables the use of anti-fall damage boots
      default: op
   easyjetpack.fly:
      description: Enables the use of the jetpack
      default: op