name: EasyJetpack
main: com.github.jselby.easyjetpack.EasyJetpack
version: 0.6
permissions:
   easyjetpack.*:
      description: All permissions in EasyJetpack
      children:
        easyjetpack.softlanding: true
        easyjetpack.fly: true
        easyjetpack.fuelless: true
        easyjetpack.admin: true
   easyjetpack.softlanding:
      description: Enables the use of anti-fall damage boots
      default: op
   easyjetpack.fly:
      description: Enables the use of the jetpack
      default: op
   easyjetpack.fuelless:
      description: Fly without fuel
      default: op
   easyjetpack.admin:
      description: Admin commands
      default: op
commands:
   easyjetpack:
      description: Various EasyJetpack admin commmands
      usage: /easyjetpack
      permission: easyjetpack.admin
   ej:
      description: Shortcut for /easyjetpack
      usage: /easyjetpack
      permission: easyjetpack.admin
      
