name: EasyJetpack
main: com.github.jselby.ej.EasyJetpack
version: 0.7
author: j_selby
permissions:
   easyjetpack.jetpackname:
      description: Allows a player to use a jetpack
      default: op
   easyjetpack.admin:
      description: Allows access to /ej
      default: op
commands:
   ej:
      description: Various EasyJetpack admin commmands
      usage: /ej
      
